[/usr/local/lib/libcnbpcnclapicom2.so]
libdl.so.2 /compat/linux/usr/lib64/libdl.so.2
libc.so.6 /compat/linux/usr/lib64/libc.so.6

[/usr/local/lib/libcnnet2.so]
libdl.so.2 /compat/linux/usr/lib64/libdl.so.2
libc.so.6 /compat/linux/usr/lib64/libc.so.6
libpthread.so.0 /compat/linux/usr/lib64/libpthread.so.0

[/compat/linux/usr/lib64/libc.so.6]
ld-linux-x86-64.so.2 /compat/linux/usr/lib64/ld-linux-x86-64.so.2
